version: "2"
services:
  db:
    image: postgres
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: mix phoenix.server
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
